# Generated by Django 5.0 on 2023-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(),
        ),
    ]
